const root=document.documentElement,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,fine=matchMedia('(pointer:fine)').matches;
const boot=document.querySelector('.boot'),counter=document.querySelector('.boot-count');
if(reduced){boot.remove()}else{let n=0;const timer=setInterval(()=>{n=Math.min(100,n+Math.ceil((100-n)*.18));counter.textContent=String(n).padStart(2,'0');if(n===100){clearInterval(timer);setTimeout(()=>boot.classList.add('done'),180)}},35)}
const cursor=document.querySelector('.cursor');if(fine){addEventListener('pointermove',e=>{root.style.setProperty('--x',e.clientX+'px');root.style.setProperty('--y',e.clientY+'px');cursor.style.translate=`${e.clientX}px ${e.clientY}px`});document.querySelectorAll('a').forEach(a=>{a.addEventListener('pointerenter',()=>cursor.classList.add(a.classList.contains('portal')?'portal-mode':'active'));a.addEventListener('pointerleave',()=>cursor.className='cursor')});document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.16}px,${(e.clientY-r.top-r.height/2)*.16}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')})}
requestAnimationFrame(()=>document.querySelectorAll('.intro-reveal').forEach((el,i)=>setTimeout(()=>el.classList.add('in'),750+i*130)));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.16});document.querySelectorAll('.observe').forEach(el=>io.observe(el));
const progress=document.querySelector('.scroll-progress i');addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight,ratio=max?scrollY/max:0;progress.style.transform=`scaleX(${ratio})`;root.style.setProperty('--scroll',ratio)}, {passive:true});
document.querySelectorAll('.portal').forEach(card=>{card.addEventListener('pointermove',e=>{if(!fine||reduced)return;const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.setProperty('--rx',(-y*3.5)+'deg');card.style.setProperty('--ry',(x*4.5)+'deg');card.style.setProperty('--mx',((x+.5)*100)+'%');card.style.setProperty('--my',((y+.5)*100)+'%')});card.addEventListener('pointerleave',()=>{card.style.setProperty('--rx','0deg');card.style.setProperty('--ry','0deg')})});

const worldMap=new Map([['portal-aki','aki'],['portal-social','social'],['portal-sierra','sierra']]),railLinks=document.querySelectorAll('.world-rail a');
const setWorld=(world='')=>{document.body.dataset.world=world;railLinks.forEach(link=>link.classList.toggle('is-active',link.dataset.world===world))};
const worldObserver=new IntersectionObserver(entries=>{const winner=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(winner)setWorld(worldMap.get([...winner.target.classList].find(c=>worldMap.has(c))))},{rootMargin:'-28% 0px -28%',threshold:[0,.25,.5,.75]});
const departure=document.querySelector('.departure');
document.querySelectorAll('.portal').forEach(portal=>{worldObserver.observe(portal);portal.addEventListener('pointerenter',()=>setWorld(worldMap.get([...portal.classList].find(c=>worldMap.has(c)))));portal.addEventListener('click',()=>{departure?.classList.add('is-active');setTimeout(()=>departure?.classList.remove('is-active'),900)})});
if(fine&&!reduced){addEventListener('pointermove',e=>document.querySelectorAll('[data-depth]').forEach(el=>{const d=+el.dataset.depth;el.style.translate=`${(e.clientX-innerWidth/2)*d*.08}px ${(e.clientY-innerHeight/2)*d*.08}px`}))}
const canvas=document.querySelector('#starfield'),ctx=canvas.getContext('2d',{alpha:true});let dots=[];function size(){const d=Math.min(devicePixelRatio,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(d,0,0,d,0,0);dots=Array.from({length:Math.min(95,Math.floor(innerWidth/13))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,z:Math.random()*1.5+.2}))}function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);ctx.fillStyle='#eeeae1';dots.forEach(p=>{p.y-=p.z*.045;if(p.y<0)p.y=innerHeight;ctx.globalAlpha=p.z*.16;ctx.beginPath();ctx.arc(p.x,p.y,p.z*.55,0,7);ctx.fill()});ctx.globalAlpha=1;if(!reduced)requestAnimationFrame(draw)}size();addEventListener('resize',size);draw();
